SELECT
    O.OS AS "NUMERO DA OS",
    SUM(OI.VLRSUBST) AS "VALOR DA ST"
FROM OS O
    JOIN OSITENSPRO OI ON OI.CODOS = O.CODOS
WHERE OI.VLRSUBST > 0
    AND O.DATAOSFIN IS NOT NULL
  --PARA MYSQL AND O.OS = @PARAM  
  --PARA FIREBIRD  AND O.OS = :PARAM
GROUP BY O.OS